In [10]:
import numpy as np

def d(x,y):
    if x == '-' or y == '-':
        return -2
    if x==y:
        return 3
    else:
        return -1

def nw_align(a,b):
    N = len(a)
    M = len(b)
    S = np.zeros((N+1,M+1))
    ptr = np.zeros((N+1,M+1,2))
    for i in range(N+1):
        S[i,0] = i*d('-','-')
    for j in range(M+1):
        S[0,j] = j*d('-','-')
    for i in range(1,N+1):    
        for j in range(1,M+1):    
            match = S[i-1,j-1] + d(a[i-1],b[j-1])
            delete = S[i,j-1] + d('-',b[j-1])
            insert = S[i-1,j] + d(a[i-1],'-')
            if match >= max(delete,insert):
                S[i,j] = match
                ptr[i,j] = [i-1,j-1]
            elif delete >= insert:
                S[i,j] = delete
                ptr[i,j] = [i,j-1]
            else:
                S[i,j] = insert
                ptr[i,j] = [i-1,j]
    print(S)
    print("Score :",S[N,M])
    i,j = N,M
    while (ptr[i,j,0]!=0 or ptr[i,j,1]!=0):
        print(ptr[i,j])
        i,j = int(ptr[i,j,0]),int(ptr[i,j,1])

In [12]:
nw_align("THISISFUN","HISFUN")

[[  0.  -2.  -4.  -6.  -8. -10. -12.]
 [ -2.  -1.  -3.  -5.  -7.  -9. -11.]
 [ -4.   1.  -1.  -3.  -5.  -7.  -9.]
 [ -6.  -1.   4.   2.   0.  -2.  -4.]
 [ -8.  -3.   2.   7.   5.   3.   1.]
 [-10.  -5.   0.   5.   6.   4.   2.]
 [-12.  -7.  -2.   3.   4.   5.   3.]
 [-14.  -9.  -4.   1.   6.   4.   4.]
 [-16. -11.  -6.  -1.   4.   9.   7.]
 [-18. -13.  -8.  -3.   2.   7.  12.]]
Score : 12.0
[8. 5.]
[7. 4.]
[6. 3.]
[5. 2.]
[4. 1.]
[3. 1.]
[2. 1.]
[1. 0.]
